services:
  api:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - FRONTEND_ORIGINS=https://cemex.advert.ninja,http://localhost:5173
    restart: always
    expose:
      - "8080"

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
