version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: migrationbob-api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Production
      
      FRONTEND_ORIGINS: ${FRONTEND_ORIGINS}
    expose:
      - "8080"
    restart: always

  nginx:
    image: nginx:1.25-alpine
    container_name: migrationbob-nginx
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

      - /etc/letsencrypt:/etc/letsencrypt:ro

      - ./webroot:/var/www/certbot
    restart: always
