services:
  - type: web
    name: migrationbob-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "8080"
      - key: FRONTEND_ORIGINS
        value: https://cemex.advert.ninja,http://localhost:5173
